### ISSUE TITLE
Grass won't cache

### ISSUE THREAD

**Issue by Fizz508** [SaneEngineer/No-Grass-In-Objects-NG#10] opened 2024-04-20 23:24 UTC
Gonna keep it simple.

I followed every listed step perfectly. 

I put everything from `\Plugins` in the .zip into `\Data\SKSE\Plugins`.

I tripled check the GrassControl.ini to make sure the settings that needed to be enabled were enabled.

I created the "PrecacheGrass.txt" file in the SkyrimSE.exe folder.

And every time I launch the game, I don't even reach the main menu, the game closes, and I get the pop-up that the grass finished caching.

When I check the `\Data\grass` folder it's completely empty.

This is what the "NGIO-NG.log" looks like: 
[NGIO-NG.log](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15050016/NGIO-NG.log)

I checked the "Skip" and "Only" lines, and the are each one line. So they are as they were when I intially downloaded the .zip.

And I repeat the process of creating the "PrecacheGrass.txt" file and get the same result every time, a swift crash, and no generated grass files.

I downloaded the Crash logger, but the game closes so fast, that the logger doesnt even have time to start and address what's causing the issue.

Any idea what I might be doing wrong?

**Comment by SaneEngineer** [comment] 2024-04-21 02:48
Try deleting GrassControl.ini, a new one should be created. 
No crash log will actual be generated as the game in not crashing, it is closing because cache is "completed"

**Comment by Fizz508** [comment] 2024-04-21 04:21
> Try deleting GrassControl.ini, a new one should be created. No crash log will actual be generated as the game in not crashing, it is closing because cache is "completed"

I deleted the .ini, added a new .txt file, loaded up the game, and nothing happened

**Comment by sessionsdev** [comment] 2024-04-21 04:23
There is either a bug or an error in ini documentation.

When the `Only-pregenerate-world-spaces = ""`, the plugin skips all worldspaces causing it to exit immediately with a success message.  Removing the `""` processes all worldspaces as expected.

**Comment by Fizz508** [comment] 2024-04-21 04:26
Ok so the .ini reappeared with everything that needed to be fixed. And just a word of advice, you should probably clarify what needs to be done to the .ini to avoid further confusion. Also thanks random guy for the help.

**Comment by SaneEngineer** [comment] 2024-04-21 06:16
Sorry about that, I'm glad the issue is resolved now.

**Closed by SaneEngineer** 2024-04-21 06:16 UTC
