### ISSUE TITLE
Grass Cache Files Are Missing

### ISSUE THREAD

**Issue by 0pLuS0** [SaneEngineer/No-Grass-In-Objects-NG#22] opened 2024-04-24 02:59 UTC
**Describe the bug**
I'm running SSE 1.6.640.0 using MO2 2.5.0, when I start Skyrim I get a popup message, saying the grass cache files are missing, unless I have a text file PrecacheGrass.txt next to  SkyrimSE.exe.

```I have created the  PrecacheGrass.txt and placed it in the Skyrim directory where SkyrimSE.exe is located, but every time I create the grass cache it disappears.```

**Screenshots**

![Grass Cache Files Missing](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/c4e4867a-bc83-402b-a8ad-0dbfd366bb85)

Here's a screen shot of the PrecacheGrass.txt I created in the Skyrim directory.
![PrecacheGrass txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/3c6504cc-bc32-4b28-9269-6b36f1d87e57)

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt
It disappears on me as I mentioned when I generate the grass cache, so I don't have it to upload.

**Config**
Please upload your GrassControl.ini
[GrassControl.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15087169/GrassControl.ini.txt)

**Log**
Please upload your NGIO.log here or link from pastebin
I don't have the NGIO.log when I created the grass cache, because I have been running the grass cache over several times, working on other issues.

**Additional context**
After I created the grass cache, I added it into MO2 and then I ran xLODGen, TexGen and DynDOLOD successfully.

**Comment by SaneEngineer** [comment] 2024-04-24 03:26
Is there any .gid files in your MO2 overwrites?

**Comment by 0pLuS0** [comment] 2024-04-24 03:36
Yes I can make the grass cache successfully, I just ran it over again, putting another PrecacheGrass.txt in the Skyrim directory.

Here's a screen shot...

![Grass Cache](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/a180724d-0759-403e-81bf-3ddacd7eb959)

```I forgot to mention, right when the grass cache is done, and I get the popup message saying it completed successfully that is when the PrecacheGrass.txt in the Skyrim directory disappears.```

THANKS

**Comment by SaneEngineer** [comment] 2024-04-24 03:50
PrecacheGrass.txt should be deleted when caching complete, so that caching doesn't startup again. The popup shows up because NGIO is not detecting the grass cache. You need to create a new mod from MO2 overrides and name it something like NGIO cache. I would first create a mod or move the files to there corresponding mod that generated them for the other files in your overwrites folder.

**Comment by 0pLuS0** [comment] 2024-04-24 04:03
I didn't think about the name, I always just called it ```grass cache``` in the past. As for TexGen and DynDOLOD they both recognized the grass cache existed.

It would be nice if you can make it so we can name it anything we like.

I just named it ```NGIO cache``` here's a screen shot. I'll rerun over xLODGen, TexGen, DynDOLOD and see how this goes.

THANKS

![NGIO cache](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/8c1d0493-90de-4add-bf2b-9fe9a9a05ca1)

**Comment by SaneEngineer** [comment] 2024-04-24 04:14
I meant .cgid. Name shouldn't matter, I thought you left the files in the overrides folder.

**Comment by 0pLuS0** [comment] 2024-04-24 04:31
No I didn't leave the grass cache in the overwrite folder. I right clicked Overwrite in the bottom left pane of MO2 and then clicked ```Create mod...``` and named it ```NGIO cache``` as you mentioned trying

![Create mod](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/6e39c08c-7c0f-4df1-8309-08fd54f64988)

The instructions said;

4. After you have waited, you should get a pop up message that says, Grass Caching complete, at which point you can copy the \Grass\ folder from Overwrites into a new mod in MO2.

THANKS

**Comment by 0pLuS0** [comment] 2024-04-24 04:36
I just started TexGen, notice HD Grass isn't grayed out but Grass is, TexGen recognizes the grass cache, that I just created and named ```NGIO cache```.

![TexGen](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/bece0232-fe05-4e40-8676-54b81f457c86)

THANKS

**Comment by SaneEngineer** [comment] 2024-04-24 04:37
I figured that after your response, sorry for the misunderstanding. If the grass cache was recognized as being in the folder grass wouldn't be greyed out. HD grass is always available.

**Comment by 0pLuS0** [comment] 2024-04-24 04:40
Oh my bad, HD Grass is because I'm using Complex Grass...

**Comment by SaneEngineer** [comment] 2024-04-24 04:44
Oh ok, check if the cache actually loads in game when you get chance if does load, I know what the issue is.

**Comment by 0pLuS0** [comment] 2024-04-24 04:46
Here's my DynDOLOD_SSE.ini showing I'm using ```cgid```.

![DynDOLOD_SSE ini](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/e38ffdd1-8e39-44fe-96d1-989e594944da)

I just started DynDOLOD and the ```grass``` section is not grayed out and active, showing that DynDOLOD recognizes the grass cache.

![DynDOLOD](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/a03ed193-83ca-4e1b-98c0-97837ef605e6)

**Comment by 0pLuS0** [comment] 2024-04-24 05:53
What the heck, now it's working! It doesn't like being called ```grass cache```? LOL

So what could be the issue before?

**Comment by SaneEngineer** [comment] 2024-04-24 06:04
I figured the issue might be the way I check the folder for .cgid files because if it shows up in other tools and in game than its what I am doing. I don't know why the name would be an issue but the way MO2 does things, things can get weird.

**Comment by SaneEngineer** [comment] 2024-04-24 06:23
Since this issue was fixed, I'm going to close it out.

**Closed by SaneEngineer** 2024-04-24 06:23 UTC
Labels: bug

**Comment by 0pLuS0** [comment] 2024-04-26 00:05
Odd, I've been making it ```Grass Cache``` and it's working... hmm
